name: Pull Request
on:
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Nodejs Setup
        uses: actions/setup-node@v1
      - name: Install Dependancies
        run: npm ci
      - name: Run Tests
        run: npm run test